{
 "title": "IbexDB",
 "tags": [
  "graph",
  "database",
  "benchmark"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "IbexDB Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "ibexdb_memory_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System memory usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "memory_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "IbexDB CPU Usage as percent from total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ibexdb_cpu_usage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Cpu Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_usage", "legendFormat": "__auto" }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "IbexDB Restarts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ibexdb_restarts_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "number of nodes in the graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "ibexdb_nodes_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "number of relationships in the graph",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    { "expr": "ibexdb_relationships_total", "legendFormat": "__auto" }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "queries/sec (client)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (vendor)  (rate(operations_total{vendor=\"ibex\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "queries/sec (client) per executor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum by (vendor, spawn_id)  (rate(operations_total{vendor=\"ibex\"}[1m]))",
     "legendFormat": "executor {{spawn_id}}"
    }
   ]
  },
  {
   "title": "Successful queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (vendor) (operations_total{vendor=\"ibex\"}) - sum by (vendor) (operations_error_total{vendor=\"ibex\"}) or (sum by (vendor) (operations_total{vendor=\"ibex\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (vendor)  (operations_error_total{vendor=\"ibex\"}) or vector(0)",
     "legendFormat": "all errors"
    }
   ]
  },
  {
   "title": "percentile successful queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(ibexdb_response_time_success_histogram_bucket[2m]))",
     "legendFormat": "p 50"
    },
    {
     "expr": "histogram_quantile(0.9, rate(ibexdb_response_time_success_histogram_bucket[2m]))",
     "legendFormat": "p 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(ibexdb_response_time_success_histogram_bucket[2m]))",
     "legendFormat": "p 99"
    }
   ]
  },
  {
   "title": "percentile error queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(ibexdb_response_time_error_histogram_bucket[2m]))",
     "legendFormat": "p 50"
    },
    {
     "expr": "histogram_quantile(0.9, rate(ibexdb_response_time_error_histogram_bucket[2m]))",
     "legendFormat": "p 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(ibexdb_response_time_error_histogram_bucket[2m]))",
     "legendFormat": "p 99"
    }
   ]
  },
  {
   "title": "queries deadline offset",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "ibexdb_msg_deadline_offset", "legendFormat": "ibexdb_msg_deadline_offset" },
    {
     "expr": "avg_over_time(ibexdb_msg_deadline_offset[1m])",
     "legendFormat": "avg 1m"
    }
   ]
  }
 ]
}